version: '3.8'

services:
  adminer:
    image: adminer:latest
    container_name: paww_adminer
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: pepa-linha
      ADMINER_PLUGINS: tables-filter tinymce
    networks:
      - paww_network
    restart: unless-stopped 